# Proxy service for nextcloud
---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: nextcloud
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nextcloud-service
  namespace: nextcloud
subsets:
- addresses:
  - ip: 192.168.0.221
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: nextclod-ingress
  namespace: nextcloud
spec:
  rules:
  - host: cloud.hmehra.dev
    http:
      paths:
      - backend:
          service:
            name: nextcloud-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - cloud.hmehra.dev
    secretName: nextcloud-tls-cert
---
