# Proxy service for nextcloud
---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: wordpress-service
  namespace: wordpress
subsets:
- addresses:
  - ip: 192.168.0.221
  ports:
  - port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: wordpress-ingress
  namespace: wordpress
spec:
  rules:
  - host: blog.hmehra.dev
    http:
      paths:
      - backend:
          service:
            name: wordpress-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - blog.hmehra.dev
    secretName: wordpress-tls-cert
---
